### PR TITLE
Code climate issues

### PR DESCRIPTION
**Pull request by Omarley7**

### CODE REVIEW

**Comment by Omarley7** [comment]
Only demo branch will trigger codecliamte..

**Comment by Omarley7** [comment]
I don't know why codeclimate isn't triggered, but it is possible to manually trigger analysis online. Here's the [status so far](https://codeclimate.com/github/Omarley7/DTaaS-Bachelor-new-GUI/compare/Code-climate-issues):

**Comment by Omarley7** [comment]
Should've fixed this duplication. For some reason not showing in codeclimate.
```ts
theme.transitions.create(['width'], {
    easing: theme.transitions.easing.sharp,
    duration: open
      ? theme.transitions.duration.enteringScreen
      : theme.transitions.duration.leavingScreen,
```

**Comment by SyntaxXeror** [comment]
LGTM!

**Pull request merged**
